// LOCAL ONLY: builds/scans images, never pushes or calls cloud APIs.
import {spawnSync} from 'node:child_process';
import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve,join} from 'node:path';
const root=resolve(new URL('../../',import.meta.url).pathname);
const run=(exe,args)=>{const r=spawnSync(exe,args,{cwd:root,encoding:'utf8',env:{PATH:process.env.PATH,HOME:process.env.HOME,TMPDIR:process.env.TMPDIR},maxBuffer:16e6});if(r.status!==0)throw Error('Release check failed: '+exe+' '+args[0]);return r.stdout.trim();};
const sha=b=>createHash('sha256').update(b).digest('hex');
async function context(){const entries=[];for(const dir of ['workers/media','services/media-broker','contracts/submission-media','tests/media-worker']){async function walk(path){for(const e of (await readdir(join(root,path),{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){if(['node_modules','.DS_Store'].includes(e.name))continue;const p=path+'/'+e.name;if(e.isDirectory())await walk(p);else if(e.isFile())entries.push([p,sha(await readFile(join(root,p)))]);else throw Error('Unexpected symlink in release context');}}await walk(dir);}for(const p of ['.dockerignore','tests/media-worker-media.test.mjs','tests/media-worker-remediation.test.mjs','tests/media-broker-security.test.mjs'])entries.push([p,sha(await readFile(join(root,p)))]);return sha(JSON.stringify(entries.sort()));}
export async function release(output){if(!output||!resolve(output).startsWith('/private/tmp/'))throw Error('Local /private/tmp output required');if(run('git',['status','--porcelain']))throw Error('Commit reviewed source before release');await mkdir(output,{recursive:true,mode:0o700});const provenance={source_head:run('git',['rev-parse','HEAD']),tree:run('git',['rev-parse','HEAD^{tree}']),context_sha256:await context(),platform:'linux/amd64',base:'node:24.14.1-bookworm-slim@sha256:b506e7321f176aae77317f99d67a24b272c1f09f1d10f1761f2773447d8da26c',apt_snapshot:'20261007T000000Z',images:[]};
 for(const kind of ['worker','broker']){const tag='tse-media-'+kind+':release-local';run('docker',['build','--platform','linux/amd64','-f',kind==='worker'?'workers/media/Dockerfile':'services/media-broker/Dockerfile','-t',tag,'.']);const image=JSON.parse(run('docker',['image','inspect',tag]))[0];const inventory=run('docker',['run','--rm','--network','none','--entrypoint','cat',tag,'/opt/runtime-packages.txt']);await writeFile(join(output,kind+'-packages.txt'),inventory);const test=run('docker',['run','--rm','--network','none','--read-only','--memory','2g','--cpus','2','--pids-limit','64','--tmpfs','/work:rw,size=536870912,uid=1000,gid=1000,mode=0700','--entrypoint','node',tag,...(kind==='worker'?['workers/media/entrypoint.mjs','--self-test']:['--test','tests/media-broker-security.test.mjs'])]);await writeFile(join(output,kind+'-tests.txt'),test);
 const sbom=JSON.parse(run('syft',[tag,'-o','cyclonedx-json']));let ffmpeg=null;if(kind==='worker'){ffmpeg=run('docker',['run','--rm','--network','none','--entrypoint','/opt/media/bin/ffmpeg',tag,'-version']);sbom.components ||= [];sbom.components.push({type:'application',name:'ffmpeg-custom',version:'9.0.2',purl:'pkg:generic/ffmpeg@9.0.2',properties:[{name:'source-archive-sha256',value:'8c3850283eb25fa026482078a04051e0be17347b09ef81a0849bec15a96e002e'},{name:'configure',value:ffmpeg}]});}await writeFile(join(output,kind+'-sbom.json'),JSON.stringify(sbom,null,2));const scan=JSON.parse(run('trivy',['image','--scanners','vuln','--format','json',tag]));await writeFile(join(output,kind+'-scan.json'),JSON.stringify(scan,null,2));const vulnerabilities=(scan.Results||[]).flatMap(r=>r.Vulnerabilities||[]);provenance.images.push({kind,local_config_digest:image.Id,registry_manifest_digest:null,packages_sha256:sha(inventory),ffmpeg,tests:'pass',scan_severities:Object.fromEntries(['CRITICAL','HIGH','MEDIUM','LOW','UNKNOWN'].map(s=>[s,vulnerabilities.filter(v=>v.Severity===s).length]))});
 }await writeFile(join(output,'provenance.json'),JSON.stringify(provenance,null,2));if(provenance.images.some(i=>Object.values(i.scan_severities).some(Boolean)))throw Error('Vulnerability disposition required; no release approved');return provenance;}
if(process.argv[1]===new URL(import.meta.url).pathname)release(process.argv[2]).catch(e=>{process.stderr.write(e.message+'\n');process.exitCode=1;});
