-- Intentionally left as a no-op.
--
-- Storage buckets and storage.objects policies should not be managed by direct SQL
-- writes against storage metadata tables in this repo.
--
-- See /supabase/storage-plan.md for the canonical bucket plan, access model,
-- object path conventions, and the manual setup steps to apply in Supabase.
