-- Intentionally left as a no-op.
--
-- Agreement storage is part of the manual Supabase Storage setup documented in
-- /supabase/storage-plan.md. Do not manage storage bucket metadata directly in
-- SQL migrations in this repo.
